### ISSUE TITLE
Resizing Kafka on all platforms

### ISSUE THREAD

**Issue by macobo** [PostHog/charts-clickhouse#146]
#### AWS
User ran out of kafka space on AWS. We tried `kubectl edit pvc data-posthog-posthog-kafka-0 -n posthog` but this failed since the default storage class on AWS is not resizable.

#### AWS
Default to a resizable StorageClass

## Describe alternatives you've considered

Nuke kafka from orbit - can cause data loss

**Comment by tiina303** [comment]
Tested on DigitalOcean

when someone just tries a helm upgrade with `--set kafka.persistence.size=<bigger_value>Gi` we will see an error like
```
Error: UPGRADE FAILED: cannot patch "posthog-posthog-kafka" with kind StatefulSet: StatefulSet.apps "posthog-posthog-kafka" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

Steps to do the resize (note use `df` in the kafka pod to confirm we have more space):
1. Size up pvc `kubectl edit pvc data-posthog-posthog-kafka-0 -n posthog` and change the `spec.resources.requests.storage` value accordingly
2. Delete the sts `kubectl delete sts posthog-posthog-kafka` (this doesn't lose data iiuc)
3. `helm upgrade` with the updated size in values (will recreate the sts as needed)

**Comment by tiina303** [comment]
What's left to do:

- [ ] there are some comments in PostHog/posthog.com#2202 (I didn't see in a follow-up yet)
- [ ] PostHog/posthog.com#2222 left a bunch of comments (but most importantly we need to have instructions how to get clusters with expandable volumes - sure we don't need to, but we care a lot about PostHog being easy to get started with and that's super helpful to have in a doc for us to figure out once rather than all users needing to go investigate)
- [ ] Major upgrade to the chart to make kafka default size = 20Gi with corresponding Major Upgrade notes that tell folks how they can get expandable volumes + maybe combined with RedPanda

Optional nice to have:
- [ ] Docs for expanding other pvc's (we can just link to kafka docs if we don't want to do anything extra)

**Comment by tiina303** [comment]
GCP: Checked our clusters (benchmarking & ee-test) in gcp and they have allowVolumeExpansion enabled both, makes me assume that's the default for gcp.
