### ISSUE TITLE
clickhouse-operator image is hard coded

### ISSUE THREAD

**Issue by dvirp-dt** [PostHog/charts-clickhouse#370]
### Proposed change
Currently, clickhouse-operator image can't be replaced using values.yaml file, since the image tag and repository are hardcoded to the latest.

"image: altinity/clickhouse-operator:latest"

### Alternative options
Use Helm templating to get the value from the values file like all other images.

## Additional context
Using the latest tag also can cause an unplanned version upgrade in case a newer version will use the same tag.

**Comment by guidoiaquinti** [comment]
👋 Hi @dvirp-dt! Thank you for opening this issue. 

This looks somehow similar to https://github.com/PostHog/charts-clickhouse/pull/342 (cc @navi86) where [my main concern](https://github.com/PostHog/charts-clickhouse/pull/342#issuecomment-1084667881) was about customising an upstream dependency instead of directly making the change there.

Good news is that the upstream repo is making progress into implementing a [Helm chart](https://github.com/Altinity/clickhouse-operator/pull/925) 🎉 . I'm suggesting to make those options configurable there, then we can simply use the upstream chart as dependency (like we do for all our other services).

**Comment by guidoiaquinti** [comment]
In the meantime, https://github.com/PostHog/charts-clickhouse/pull/371 will make the container image fixed so you should not experience unplanned version upgrade in case a newer version will use the same tag.

**Comment by dvirp-dt** [comment]
Hey, @guidoiaquinti thanks for your reply.

How would you suggest editing this image in case we have to? 
Deploying the chart into air-gapped environment isn't going to work without changing this image repository.

**Comment by guidoiaquinti** [comment]
> How would you suggest editing this image in case we have to?

In the meantime, if you can make the deployment process two steps, you could probably first render the templates in a temporary directory, edit the string and then apply them to k8s.

**Comment by dvirp-dt** [comment]
There is big worring telling not to edit the chart, but I guess we have to in this case.

I'll keep tracking the development process of the operator chart.
Thanks.
