### ISSUE TITLE
Generate clickhouse password dynamically

### ISSUE THREAD

**Issue by macobo** [PostHog/charts-clickhouse#43]
## Is your feature request related to a problem?

Currently, the clickhouse password is static and publicly available in this repo

## Describe the solution you'd like

Generate the data dynamically via secrets.

## Describe alternatives you've considered

Make it a mandatory variable

## Additional context

See https://github.com/Altinity/clickhouse-operator/issues/700 for context on how to implement this.

**Comment by tiina303** [comment]
Reprioritizing as we changed Clickhouse to be a Nodeport instead of a LB, i.e. it's not externally accessible anymore.

Note that https://github.com/PostHog/charts-clickhouse/pull/81 which (didn't solve the full problem) & ran into a problem if the `users.xml` didn't get properly recomputed (upgrade failed for whatever reason at inopportune time or clickhouse operator thought nothing needed to be updated) can be fixed by making the backup password (if an upgrade & we had a previous secret) to be the hardcoded one we have now and only generate new password dynamically for new installs.

See also https://github.com/PostHog/vpc/issues/165 for more context. Clickhouse operator password is stored in ConfigMap both as plaintext and sha, which I'm not sure if we can pull values from secrets for.
